# Description: This file is used to define the services that will be used in the project.
version: '3.8'

services:
  web1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web1
    networks:
      - my-network

  web2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web2
    networks:
      - my-network

  web3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web3
    networks:
      - my-network

  loadbalancer:
    build:
      context: ./loadbalancer
      dockerfile: Dockerfile
    container_name: loadbalancer
    depends_on:
      - web1
      - web2
      - web3
    networks:
      - my-network
    volumes:
      - haproxy-config:/usr/local/etc/haproxy    

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: proxy
    depends_on:
      - loadbalancer
    ports:
      - "80:80"
    networks:
      - my-network


  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    container_name: controller
    depends_on:
      - loadbalancer
      - web1
      - web2
      - web3
    networks:
      - my-network
    volumes:
      - haproxy-config:/usr/local/etc/haproxy
    environment:
      - HAPROXY_CFG_PATH=/usr/local/etc/haproxy/haproxy.cfg

volumes:
  haproxy-config:

networks:
  my-network:
    driver: bridge
